# https://docs.travis-ci.com/user/deployment/pages/#further-configuration

os:
  osx

cache:
  bundler: true
  timeout: 1500
  directories:
  - $HOME/.stack
  - $HOME/.agda

before_install:
  - brew update
  - brew install ghc
  - brew install agda
  - brew install stack
  - brew install npm

script:
  - make agda2html
  - pip3 install agda-pkg
  - apkg install standard-library
