# https://docs.travis-ci.com/user/deployment/pages/#further-configuration

os:
  osx

before_install:
  - brew update
  - brew install ghc
  - brew install agda
  - brew install stack
  - brew install cask
  - brew cask install ipe
  - brew upgrade node
  - npm install --global gulp

script:
  - pwd
  - make agda2html
  - make build
  - pip3 install agda-pkg
  - apkg init
  - git clone http://github.com/agda/agda-stdlib
  - cd agda-stdlib && apkg install --no-dependencies

branches:
  only:
    - sources
