# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               jonaprieto
tagline:             'log'
description:         'Links'
url:                 'http://jonaprieto.github.io'
baseurl:             ''
# paginate:            100
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-algolia
exclude:
  - src/
  - Gemfile
  - Gemfile.lock

algolia:
  application_id: '6LC140UUTA'
  index_name:     'notes'
  search_only_api_key: '038508bea0ee72e992b18935df862622'

# About/contact
author:
  name:              Jonathan Prieto-Cubides
  url:               https://github.com/jonaprieto
  email:             prieto.jona@gmail.com

# Custom vars
version:             0.0.1
