# Setup
title:               jonaprieto
tagline:             'logs in progress'
description:         'Jonathan Prieto-Cubides'
url:                 'http://jonaprieto.github.io'
baseurl:             ''
timezone:            'Europe/Oslo'
# paginate:            100

highlighter: rouge
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-algolia
  - jekyll-toc
  - jekyll-git_metadata

exclude:
  - src/
  - Gemfile
  - Gemfile.lock

# ----------------------------------------------------------------------------
algolia:
  application_id: '6LC140UUTA'
  index_name: 'notes'
  search_only_api_key: '038508bea0ee72e992b18935df862622'
  extensions_to_index: 'html,md,lagda,agda'
  nodes_to_index:
    'p,blockquote,pre'
  files_to_exclude:
      - src/*
      - index.html
      - _index.html
  settings:
    # for unicode-input
    separatorsToIndex: '$+-/=@¼½¾×ƛƛː˸ΑΒΓΔΕΖΘΙΚΛΜΝΞΡΣΤΥΦΧΨΩαβγδεζθικλμνξρστυφχψω፥፦–—••‣‣′″‴‵‶‷‼‽‿⁀⁂⁅⁆⁇⁈⁉⁌⁍⁎⁑⁗⁽⁾₍₎ℂℍℕℙℚℝℤℼℽℾℿ⅀⅀⅋⅓⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞⅟←←←↑↑→→→↓↓↔↔↔↕↕↖↖↗↗↘↘↙↙↚↚↚↛↛↛↜↜↝↝↞↞↟↟↠↠↡↡↢↢↣↣↤↤↥↥↦↦↧↧↨↨↩↪↫↬↭↭↮↮↮↯↯↰↱↲↳↴↵↶↷↸↹↺↻↼↽↾↿⇀⇁⇂⇃⇄⇄⇅⇅⇆⇆⇇⇇⇈⇈⇉⇉⇊⇊⇋⇌⇍⇍⇎⇎⇎⇏⇏⇏⇐⇐⇑⇑⇒⇒⇒⇓⇓⇔⇔⇔⇕⇕⇖⇖⇗⇗⇘⇘⇙⇙⇚⇚⇛⇛⇜⇜⇝⇝⇞⇟⇠⇡⇢⇣⇤⇥⇦⇧⇨⇩⇪⇫⇬⇭⇮⇯⇰⇱⇲⇳⇴⇵⇵⇶⇶⇷⇸⇹⇺⇻⇼⇽⇾⇿∀∁∃∄∅∆∈∉∉∊∋∌∌∍∎∏∐∑∔∘∘∙∛∜∞∟∡∢∣∤∥∦∧∧∨∨∩∩∪∪∫∬∭∮∯∰∱∲∳∶∷∸∹∺∻∻∼∼∽∾∿≀≁≁≂≂≃≃≄≄≅≅≆≇≇≈≈≉≉≊≊≋≋≌≍≎≏≐≐≑≑≒≓≔≔≕≕≖≗≗≘≘≙≙≚≚≛≛≜≜≝≝≞≞≟≟≠≠≡≡≢≢≣≣≤≤≥≥≦≧≨≩≪≫≬≭≮≮≯≯≰≰≰≱≱≱≲≲≳≳≴≴≵≵≶≷≸≹≺≻≼≽≾≿⊀⊁⊂⊂⊃⊃⊄⊄⊅⊅⊆⊆⊇⊇⊈⊈⊉⊉⊊⊋⊌⊍⊍⊎⊎⊏⊏⊐⊐⊑⊑⊒⊒⊓⊓⊔⊔⊕⊖⊗⊘⊙⊚⊛⊜⊝⊞⊟⊠⊡⊢⊢⊣⊣⊤⊥⊦⊧⊨⊨⊩⊩⊪⊪⊫⊫⊬⊬⊭⊭⊮⊮⊯⊯⊰⊱⊲⊳⊴⊵⊸⊸⊸⊹⊻⊼⊽⊾⊿⋀⋀⋁⋁⋂⋂⋃⋃⋆⋆⋈⋉⋊⋋⋌⋍⋎⋏⋐⋑⋒⋓⋕⋖⋗⋘⋙⋚⋛⋜⋝⋞⋟⋠⋡⋢⋢⋣⋣⋤⋥⋦⋦⋧⋧⋨⋩⋪⋫⋬⋭⋮⋯⋰⋱⋲⋳⋴⋵⋶⋷⋸⋹⋺⋻⋼⋽⋾⋿⌈⌈⌈⌉⌉⌉⌊⌊⌊⌋⌋⌋⌜⌜⌜⌝⌝⌝⌞⌞⌞⌟⌟⌟〈〉⌶⌷⌸⌹⌺⌻⌼⌽⌾⌿⍀⍁⍂⍃⍄⍅⍆⍇⍈⍉⍊⍋⍌⍍⍎⍏⍐⍑⍒⍓⍔⍕⍖⍗⍘⍙⍚⍛⍜⍝⍞⍟⍟⍠⍡⍢⍣⍤⍥⍦⍧⍨⍩⍪⍫⍬⍭⍮⍯⍰⍱⍲⍳⍴⍵⍶⍷⍸⍹⍺⎕⎴⎵─━│┃┄┅┆┇┈┉┊┋┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋╌╍╎╏═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬╭╮╯╰╱╲╳╴╵╶╷╸╹╺╻╼╽╾╿■■□□▢▢▣▣▤▥▦▧▨▩▬▬▭▭▮▮▯▯▰▰▱▱▲▲△△▴▴▵▵▶▶▷▷▸▸▹▹►►▻▻▼▼▽▽▾▾▿▿◀◀◁◁◂◂◃◃◄◄◅◅◆◆◇◇◈◈○○◌◌◍◎◎●●◐◑◒◓◔◕◖◗◠◡◢◢◣◣◤◤◥◥◦◦◧◨◩◪◫◬◭◮◯◯◰◱◲◳◴◵◶◷◸◸◹◹◺◺◻◻◼◼◽◽◾◾◿◿★☆♩♪♫♬♭♯⚀⚁⚂⚃⚄⚅⚆⚇⚈⚉✂✄'
# ----------------------------------------------------------------------------

# About/contact
author:
  name:              Jonathan Prieto-Cubides
  url:               https://github.com/jonaprieto
  email:             prieto.jona@gmail.com

# Custom vars
version:             0.0.2
