# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               jonaprieto
tagline:             'logs in progress'
description:         'This is my blog, everything is in progress, if you found
                      something interesting/useful good for you. Let me know and cheers!'
url:                 'http://jonaprieto.github.io'
baseurl:             ''
timezone:            'Europe/Oslo'
# paginate:            100
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-algolia
  - jekyll-tocw

exclude:
  - src/
  - Gemfile
  - Gemfile.lock

# ----------------------------------------------------------------------------
algolia:
  application_id: '6LC140UUTA'
  index_name:     'notes'
  search_only_api_key: '038508bea0ee72e992b18935df862622'
  extensions_to_index: 'html,md,lagda,agda'
  nodes_to_index: 'p,blockquote,pre'
  files_to_exclude:
    - src/*
    - index.html
    - _index.html
  settings:
    # for unicode-input
    separatorsToIndex: '∼∽≈≋∻∾∿≀≃⋍≂≅≌≊≡≣≐≑≒≓≔≕≖≗≘≙≚≛≜≝≞≟≍≎≏≬⋕≠≁≉≄≇≆≢≭≠∼≁≈≉≋∻≃≄≂≅≇≊≡≢≣≐≑≔≕≗≘≙≚≛≜≝≞≟≪⋘≤≦≲≶≺≼≾⊂⊆⋐⊏⊑⊰⊲⊴⋖⋚⋜⋞≮≰≨≴⋦≸⊀⋨⊄⊈⊊⋢⋤⋪⋬⋠≫⋙≥≧≳≷≻≽≿⊃⊇⋑⊐⊒⊱⊳⊵⋗⋛⋝⋟≯≱≩≵⋧≹⊁⋩⊅⊉⊋⋣⋥⋫⋭⋡≤≥≰≱≰≱≮≯≲≳⋦⋧≴≵⊂⊃⊄⊅⊆⊇⊈⊉⊏⊐⊑⊒⋢⋣∈∉∊∋∌∍⋲⋳⋴⋵⋶⋷⋸⋹⋺⋻⋼⋽⋾⋿∉∌∩⋂∧⋀⋏⨇⊓⨅⋒∏⊼⨉∪⋃∨⋁⋎⨈⊔⨆⋓∐⨿⊽⊻⊍⨃⊎⨄⊌∑⅀∧∨⋀⋁∩∪⊎⊍⋂⋃⨄⨃⊓⊔⨅⨆⊢⊣⊤⊥⊦⊧⊨⊩⊪⊫⊬⊭⊮⊯⊢⊬⊣⊨⊭⊩⊮⊫⊯⊪∣∤∥∦∀∃∄∅∁⌜⌝⌞⌟⌈⌉⌊⌋⌜⌝⌈⌉⌞⌟⌊⌋⌜⌈⌝⌉⌞⌊⌟⌋∎×∘∘∙⋆∔∸∶⦂ː꞉˸፥፦：﹕︓∷∺∹⊹∛∜∆∞⅋⊕⊖⊗⊘⊙⊚⊛⊜⊝⨁⨂⨀⍟⊞⊟⊠⊡∫∬∭∮∯∰∱∲∳∟∡∢⊾⊿⋈⋉⋊⋋⋌⨝⟕⟖⟗←⇐⇚⇇⇆↤⇦↞↼↽⇠⇺↜⇽⟵⟸↚⇍⇷↹↢↩↫⇋⇜⇤⟻⟽⤆↶↺⟲→⇒⇛⇉⇄↦⇨↠⇀⇁⇢⇻↝⇾⟶⟹↛⇏⇸⇶↴↣↪↬⇌⇝⇥⟼⟾⤇↷↻⟳⇰⇴⟴⟿➵➸➙➔➛➜➝➞➟➠➡➢➣➤➧➨➩➪➫➬➭➮➯➱➲➳➺➻➼➽➾⊸↑⇑⟰⇈⇅↥⇧↟↿↾⇡⇞↰↱➦⇪⇫⇬⇭⇮⇯↓⇓⟱⇊⇵↧⇩↡⇃⇂⇣⇟↵↲↳➥↯↕⇕↨⇳↔⇔⇼↭⇿⟷⟺↮⇎⇹↖⇖⇱↸↗⇗➶➹➚↘⇘⇲➴➷➘↙⇙←←⇐→→⇒⇒↑⇑↓⇓↕⇕↔↔⇔⇔↖⇖↗⇗↘⇘↙⇙⇚⇇⇆⇛⇉⇶⇄⟰⇈⇅⟱⇊⇵⟵⟵↜⇜⟶⟶↝⇝⟿⟷⟷↭↚↚⇍↛↛⇏⇏↮↮⇎⇎↤↞↦↠↥↟↧↡↨↢↣⊸⊸↯⋯⋮⋰⋱─│┌┐└┘├┤┬┼┴╴╵╶╷╭╮╯╰╱╲╳═║╔╗╚╝╠╣╦╬╩╒╕╘╛╞╡╤╪╧╓╖╙╜╟╢╥╫╨━┃┏┓┗┛┣┫┳╋┻╸╹╺╻┍┯┑┕┷┙┝┿┥┎┰┒┖┸┚┠╂┨┞╀┦┟╁┧┢╈┪┡╇┩┮┭┶┵┾┽┲┱┺┹╊╉╆╅╄╃╿╽╼╾╌╎┄┆┈┊╍╏┅┇┉┋◂◃◄◅▸▹►▻▴▵▾▿◢◿◣◺◤◸◥◹◀◁▶▷▲△▼▽◬◭◮◂▸▴▾◄►◢◣◤◥◃▹▵▿◅▻◿◺◸◹◀▶▲▼◁▷△▽■□◼◻◾◽▣▢▤▥▦▧▨▩◧◨◩◪◫◰◱◲◳■◼◾□◻◽▣▢▬▭▮▯▬▮▭▯▰▱▰▱◆◇◈◆◇◈●○◎◌◯◍◐◑◒◓◔◕◖◗◠◡◴◵◶◷⚆⚇⚈⚉●○◎◌◯⋆✦✧✶✴✹★☆✪✫✯✰✵✷✸✦✧✶✴✹𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤℾℿ⅀𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫ℽℼ𝟘𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗⁅⁽₍〈⎴⟅⟦⟨⟪⦃〈《「『【〔〖〚︵︷︹︻︽︿﹁﹃﹙﹛﹝（［｛｢⁆⁾₎〉⎵⟆⟧⟩⟫⦄〉》」』】〕〗〛︶︸︺︼︾﹀﹂﹄﹚﹜﹞）］｝｣⟦⟧⟨⟩⟪⟫⦃⦄⟅⟆⟅⟆⦇⦈′″‴⁗‵‶‷¼½¾⅓⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞⅟•◦‣⁌⁍•◦‣♩♪♫♬♭♯–—‼⁇‽⁈⁉⚀⚁⚂⚃⚄⚅⁎⁑⁂✢✣✤✥✱✲✳✺✻✼✽❃❉❊❋✂✄⁀‿⌶⌷⌸⌹⌺⌻⌼⌽⌾⌿⍀⍁⍂⍃⍄⍅⍆⍇⍈⍉⍊⍋⍌⍍⍎⍏⍐⍑⍒⍓⍔⍕⍖⍗⍘⍙⍚⍛⍜⍝⍞⍟⍠⍡⍢⍣⍤⍥⍦⍧⍨⍩⍪⍫⍬⍭⍮⍯⍰⍱⍲⍳⍴⍵⍶⍷⍸⍹⍺⎕̧̣̱̲̳̰̣̤͍̭̯̪̬̮̺̀́̂̃̄̆̇̈̋̌̅̿̃͌̇̈⃛⃜⃖⃐⃔⃖⃗⃑⃕⃗⃡̂̑͆̌̆ƛαΑβΒγΓδΔεΕζΖθΘιΙκΚλΛƛμΜνΝξΞρΡσΣτΤυΥφΦχΧψΨωΩ𝐴𝐵𝐶𝐷𝐸𝐹𝐺𝐻𝐼𝐽𝐾𝐿𝑀𝑁𝑂𝑃𝑄𝑅𝑆𝑇𝑈𝑉𝑊𝑋𝑌𝑍𝑎𝑏𝑐𝑑𝑒𝑓𝑔𝑖𝑗𝑘𝑙𝑚𝑛𝑜𝑝𝑞𝑟𝑠𝑡𝑢𝑣𝑤𝑥𝑦𝑧𝑨𝑩𝑪𝑫𝑬𝑭𝑮𝑯𝑰𝑱𝑲𝑳𝑴𝑵𝑶𝑷𝑸𝑹𝑺𝑻𝑼𝑽𝑾𝑿𝒀𝒁𝒂𝒃𝒄𝒅𝒆𝒇𝒈𝒉𝒊𝒋𝒌𝒍𝒎𝒏𝒐𝒑𝒒𝒓𝒔𝒕𝒖𝒗𝒘𝒙𝒚𝒛𝒜𝒞𝒟𝒢𝒥𝒦𝒩𝒪𝒫𝒬𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝒻𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃𝔄𝔅𝔇𝔈𝔉𝔊𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔𝔖𝔗𝔘𝔙𝔚𝔛𝔜𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻᴬᴮᴰᴱᴳᴴᴵᴶᴷᴸᴹᴺᴼᴾᴿᵀᵁⱽᵂ¡¢¦°¿ªº⓪⑴①⒈❶➀➊⑵②⒉❷➁➋⑶③⒊❸➂➌⑷④⒋❹➃➍⑸⑤⒌❺➄➎⑹⑥⒍❻➅➏⑺⑦⒎❼➆➐⑻⑧⒏❽➇➑⑼⑨⒐❾➈➒⑽⑩⒑❿➉➓⑾⑪⒒⑿⑫⒓⒀⑬⒔⒁⑭⒕⒂⑮⒖⒃⑯⒗⒄⑰⒘⒅⑱⒙⒆⑲⒚⒇⑳⒛⒜Ⓐⓐ⒝Ⓑⓑ⒞Ⓒⓒ⒟Ⓓⓓ⒠Ⓔⓔ⒡Ⓕⓕ⒢Ⓖⓖ⒣Ⓗⓗ⒤Ⓘⓘ⒥Ⓙⓙ⒦Ⓚⓚ⒧Ⓛⓛ⒨Ⓜⓜ⒩Ⓝⓝ⒪Ⓞⓞ⒫Ⓟⓟ⒬Ⓠⓠ⒭Ⓡⓡ⒮Ⓢⓢ⒯Ⓣⓣ⒰Ⓤⓤ⒱Ⓥⓥ⒲Ⓦⓦ⒳Ⓧⓧ⒴Ⓨⓨ⒵Ⓩⓩ∏'
# ----------------------------------------------------------------------------

# About/contact
author:
  name:              Jonathan Prieto-Cubides
  url:               https://github.com/jonaprieto
  email:             prieto.jona@gmail.com

# Custom vars
version:             0.0.2
