# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               jonaprieto
tagline:             'notes'
description:         'Links'
url:                 'http://jonaprieto.github.io'
baseurl:             ''
paginate:            100
markdown: kramdown

plugins:
  - jekyll-feed
exclude:
  - src/
  - Gemfile
  - Gemfile.lock
# About/contact
author:
  name:              Jonathan Prieto-Cubides
  url:               https://github.com/jonaprieto
  email:             prieto.jona@gmail.com

# Custom vars
version:             0.0.1
