# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               jonaprieto
tagline:             'log'
description:         'Links'
url:                 'http://jonaprieto.github.io'
baseurl:             ''
# paginate:            100
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-algolia
  - jekyll-analytics
  - disqus-for-jekyll

exclude:
  - src/
  - Gemfile
  - Gemfile.lock

algolia:
  application_id: '6LC140UUTA'
  index_name:     'notes'
  search_only_api_key: '038508bea0ee72e992b18935df862622'

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-114360791-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

disqus:
  name: "jonaprieto-blog" # required
  noscript: "Your noscript tag message." # optional
  
# About/contact
author:
  name:              Jonathan Prieto-Cubides
  url:               https://github.com/jonaprieto
  email:             prieto.jona@gmail.com

# Custom vars
version:             0.0.1
