dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="4.06.0+32bit"

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam update
- opam config var root
- ./toolchain-setup.sh
- opam list
- make coq-get
- make coq-build

script:
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- ./build.sh
- git submodule update --remote
- cd ui-external/CodeMirror && npm install
- echo -en 'travis_fold:end:jscoq.build\\r'
